Repository hypered/curiosity, pull requests merged in 2022-08, with the labels that each got.

#45 Fix quotes in UserName blacklist.
  src/Curiosity/Data/User.hs
  src/Curiosity/Server.hs
Labels: bug

#50 Start simple operations for users
  bin/cty.hs
  curiosity.cabal
  data/alice.json
  data/bob-0.json
  data/bob-1.json
  data/bob-2.json
  data/charlie.json
  machine/configuration.nix
  modules/curiosity.nix
  src/Curiosity/Command.hs
  src/Curiosity/Data/User.hs
  src/Curiosity/Html/Homepage.hs
  src/Curiosity/Html/Profile.hs
  src/Curiosity/Parse.hs
  src/Curiosity/Run.hs
  src/Curiosity/Runtime.hs
  src/Curiosity/Server.hs
  tests/CuriositySpec.hs
Labels: draft

#46 State.json: use PrettyJSON.
  src/Curiosity/Server.hs
Labels: enhancement

#49 Nix attribute to build a Docker image
  README.md
  default.nix
  docker/default.nix
  machine/configuration.nix
  src/Curiosity/Run.hs
Labels: draft
